// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_aDTeX6g_RDlgH4Tu0tOC-rW5uLM8F5o',
    appId: '1:599220831701:web:64a2dbbd38545cc40ca95c',
    messagingSenderId: '599220831701',
    projectId: 'proj-auth-84f46',
    authDomain: 'proj-auth-84f46.firebaseapp.com',
    storageBucket: 'proj-auth-84f46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDG1KEqNn5VhNCsb8CzuPHa32cst0ZGA8',
    appId: '1:599220831701:android:1eeb46766b9cb6c30ca95c',
    messagingSenderId: '599220831701',
    projectId: 'proj-auth-84f46',
    storageBucket: 'proj-auth-84f46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFJ5KztMellcAs5IMkipTy6pI06UTpqG4',
    appId: '1:599220831701:ios:8ad61cabfd8af5a80ca95c',
    messagingSenderId: '599220831701',
    projectId: 'proj-auth-84f46',
    storageBucket: 'proj-auth-84f46.firebasestorage.app',
    androidClientId: '599220831701-95v0djr7qo20g5a5311gb4kvd3jq50fc.apps.googleusercontent.com',
    iosClientId: '599220831701-l39846nbtp8slbutgouiuc34hfnnacld.apps.googleusercontent.com',
    iosBundleId: 'com.example.projLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFJ5KztMellcAs5IMkipTy6pI06UTpqG4',
    appId: '1:599220831701:ios:8ad61cabfd8af5a80ca95c',
    messagingSenderId: '599220831701',
    projectId: 'proj-auth-84f46',
    storageBucket: 'proj-auth-84f46.firebasestorage.app',
    androidClientId: '599220831701-95v0djr7qo20g5a5311gb4kvd3jq50fc.apps.googleusercontent.com',
    iosClientId: '599220831701-l39846nbtp8slbutgouiuc34hfnnacld.apps.googleusercontent.com',
    iosBundleId: 'com.example.projLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_aDTeX6g_RDlgH4Tu0tOC-rW5uLM8F5o',
    appId: '1:599220831701:web:596d94c5d00a3d1f0ca95c',
    messagingSenderId: '599220831701',
    projectId: 'proj-auth-84f46',
    authDomain: 'proj-auth-84f46.firebaseapp.com',
    storageBucket: 'proj-auth-84f46.firebasestorage.app',
  );

}